apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /dapr/secrets/docker.json

## For Tye / Local
#./dapr/secrets/local.json

## For Docker
#/dapr/secrets/docker.json