name: docker-push

on:
  workflow_dispatch: 

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  docker:
    name:  Docker Build & Push
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      working-directory: ./
      if: ${{ github.ref == 'refs/heads/main' && success() }}
      run: | 
        dotnet publish src/api-gateway/Gateway/Gateway.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fsh-microservices.gateway
        dotnet publish src/identity-server/Host/Host.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fsh-microservices.identity
        dotnet publish src/services/catalog/Host/Host.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fsh-microservices.catalog
    - name: Publish Docker Image
      if: ${{ github.ref == 'refs/heads/main' && success() }}
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fsh-microservices.gateway --all-tags
        docker push ${{ secrets.DOCKER_USERNAME }}/fsh-microservices.identity --all-tags
        docker push ${{ secrets.DOCKER_USERNAME }}/fsh-microservices.catalog --all-tags
